In [5]:
import pandas as pd
import numpy as np
import torch as tr
import torch.nn as nn
import torch.nn.functional as F

In [21]:
df_train = pd.read_csv('./train.csv')
np_train_x = np.reshape(df_train.values[:, 1:].astype(np.uint8), (28, 28,df_train.shape[0]))
np_train_y = np.reshape(df_train.values[:, 0].astype(np.uint8), (1, df_train.shape[0]))
df_test = pd.read_csv('./test.csv')
np_test_x = np.reshape(df_test.values.astype(np.uint8), (28, 28, df_test.shape[0]))

In [22]:
print(np_train_x.size)
print(np_train_x)

32928000
[[[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   9 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 ...

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ... 119   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ... 

In [25]:
print(np_train_x[:,:,1000])

[[104   0 253   0   0   0   0   0   0  15   0   0   0 253 153   0   0   0
    0   0   0   0 164   0   0   0   0   0]
 [ 21   0   0   0  19   0   0   0   0   0   0   0   0 253   0   0 152   0
    0   0   0 255   0 182   0   0   0 148]
 [  0   0  84   0 212   0   0   0   0 252   0   0   0 251 254   0   0   0
  178   0  18 219   0   0   0   0   0   0]
 [228   0   0   0 253   0  93   0   0 253   0   0   0   3   0   0   0   0
    0   0   0  56   0 149   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0 253   0   0   0
  253   0   0   0   0   0   0   0   0   0]
 [224   0   0   0 254   0 253   0   0   0   0   0   0 253 254   0   0   0
  253   0   0   0   0 254   0   0   0   0]
 [196   0 123   0   0 192 141   0   0   0   0   0   0   0 253   0 140   0
    0   0   0 122   0   0   0   0   0   0]
 [  0   0   0   0   0 135   0  76   0   0   0 253   0 118   0   0   0   0
  182   0 187   0   0 229   0   0   0   0]
 [  0   0   0   0   0   0  42 147   8   0   0   0   0   0 253   

In [16]:
np_train_x.shape

(28, 28, 42000)